<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Comparative Neurogenomic Databases</title>

<link href="css/dbmain.css" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
.style1 {color: #FF0000}
-->
</style>
</head>

<body class="mainPage" onload="MM_preloadImages('images/layout/rollovers/home_over.jpg','images/layout/rollovers/background_over.jpg','images/layout/rollovers/pre_over.jpg','images/layout/rollovers/post_over.jpg','images/layout/rollovers/regulatory_over.jpg','images/layout/rollovers/proposal_over.jpg')">
<div id="container">
	<div id="dbHeader"></div>
    <?php include('includes/dbmainNav.php');?>
	<div id="content" style="clear:both;">
    	<div id="memberLogIn"></div>
   	  <div id="leftContent">
   	    <p>Nervous systems  are among of the most complex tissues ever found in animals. Across diverse  animal phyla they represent unique examples of parallel evolution and possible results  of independent origins of complex brains (and even neurons) in different lineages. <br />
   	      <br />
This page is  home to comparative neurogenomic databases, <strong><em>Slime  Base</em></strong> and <strong><em>BlastQuest</em></strong>.  Together, these databases represent one of the largest independent collections  of molluscan sequence data including sequences from <em>Aplysia</em>, <em>Pleurobranchaea,</em> <em>Lymnaea</em>, <em>Tritonia</em>, <em>Melibe</em>, and <em>Clione</em>. In  addition, we offer the emerging genomic resources from representative of basal  Metazoans and basal Deuterostomes and selected arthropods known to be crucial  for our understanding of animal evolution.<br />
<br />
All of the data  are original and were generated by the Moroz  laboratory (Whitney Laboratory for Marine  Biosciences, University   of Florida) as a  part of the ongoing initiatives in Marine Genomics and singe neuron  transcriptome analysis.<br />
   	    <br />
   	    </p>
        <p><strong>Please select a database below  to get started.</strong></p>
        <p>&nbsp;</p>
        <div id="leftDB">
        
       	  <h1 style='color:#006633;'><a href="slimebase/slimebase.php"><img src="images/layout/slimebase_enter.jpg" alt="Enter SlimeBase" width="257" height="118" border="0" /></a></h1>
          <p>*SlimeBase requires the latest <br />Adobe Flash Player. Get it <a href='http://www.adobe.com/products/flashplayer/'>here.</a>   <br />
            <br />
          </p>
          <p>
          	<a href="/slimebase/description.php">read more...</a><br />
            <a href="/slimebase/tutorials.php">tutorials</a>    <br />
<br />
			   </p>
        </div>
      <div id="rightDB">
      
       	<h1 style='color:#FF9900;'><a href="http://mascot.biotech.ufl.edu/bq/"><img src="images/layout/bq_enter.jpg" alt="Enter BlastQuest" width="257" height="118" border="0" /></a></h1>
           <p align="left">username: <span class="style1">matt</span><br />
password: <span class="style1">matt</span><br />
<br />
<span class="style1"><a href="http://mascot.biotech.ufl.edu/bq/" style='color: #FF0000;'>Please enter the above username and password at the BQ login on the next page.</a></span></p>
<br />
          <p>
           	  <a href='bq/bq-dke.pdf' target='_blank'>read more...</a><br /><br />
            </p>
        </div>
        <br />
        <div style="float:left; width:600px; margin-top: 45px;">
        <h2>Organisms</h2>
        <div style="float:left; width: 600px; overflow:auto;">
        	<div id="organisms"><img src="seq_view/images/main_page/aplysia.jpg" alt="Aplysia californica" width="137" height="100" /><img src="seq_view/images/main_page/pleurobranchaea.jpg" alt="Pleurobranchaea californica" width="149" height="100" /><img src="seq_view/images/main_page/tritonia.jpg" alt="Tritonia diomedea" width="135" height="100" /><img src="seq_view/images/main_page/lymnaea.jpg" alt="Lymnaea stagnalis" /><img src="seq_view/images/main_page/clione.jpg" alt="Clione limacina" /><img src="seq_view/images/main_page/xenoturbellida.jpg" alt="Xenoturbella bocki" /><img src="seq_view/images/main_page/octopus.jpg" alt="Octopus vulgaris" /><img src="seq_view/images/main_page/nautilus.jpg" alt="Nautilus pompilius" /><img src="seq_view/images/main_page/loligo.jpg" alt="Loligo opalescens" /><img src="seq_view/images/main_page/cancer_borealis.jpg" alt="Cancer borealis" /><img src="seq_view/images/main_page/aglantha.jpg" alt="Aglantha digitale" /><img src="seq_view/images/main_page/beroe.jpg" alt="e sp." /><img src="seq_view/images/main_page/pleurobrachia.jpg" alt="Pleurobrachia bachei" /><img src="seq_view/images/main_page/placozoa.jpg" alt="Trichoplax adharens" /></div></div>
        </div>
   	  </div>
      <div class="quickLinks">
      	<div id="rightContent">
        <div id="linkContainer">
        <h1>Quick Links</h1>
      	  <p><a href="http://10.41.128.72/admin/seq_view/flash/tdb_prototype.html">SlimeBase</a><br />
          <a href="http://mascot.biotech.ufl.edu/bq/">BlastQuest</a>
          <a href="http://www.whitney.ufl.edu/research_programs/moroz.htm">Whitney Lab</a>
          <a href="http://www.ncbi.nlm.nih.gov/">NCBI</a><br />
          <a href="http://www.broadinstitute.org/science/projects/mammals-models/vertebrates-invertebrates/aplysia/aplysia-genome-sequencing-project">Aplysia@Broad</a>
          <br />
          <br />
          <h1>Collaborators:</h1>

								   Anna DiCosmo 
<br />
   Carlo DiCristo
<br />
   Rhanor Gillette<br />

								   Dirk Bucher
<br />
   Paul Katz<br />

								   Michael Thorndyke<br />
                                   Peter Burbach<br />

								   David Schultz<br />

								   Eric Kandel<br />

   Jingyue Ju
   	      </p>
      	  </div>
          <p>
</p>
      	</div>
   	  </div>
  </div>
	<div id="footer"></div>
</div>
</body>
</html>
